name: Install HDF4
runs:
  using: "composite"
  steps:
    - name: Install HDF4 (via apt-get)
      shell: bash
      if: runner.os == 'Linux'
      run: |
          echo "::group::Install HDF4 (via apt-get)"
          sudo apt-get -y update && sudo apt-get install --no-install-recommends -y libhdf4-alt-dev
          echo "::endgroup::"
# formula is broken as of 2024-12-03 "no formula szip"
#    - name: Install HDF4 (via brew)
#      shell: bash
#      if: runner.os == 'macOS'
#      run: |
#          echo "::group::Install HDF4 (via brew)"
#          brew install brewsci/science/hdf4
#          echo "::endgroup::"
