name: Install Proj
runs:
  using: "composite"
  steps:
    - name: Install Proj (via apt-get)
      shell: bash
      if: runner.os == 'Linux'
      run: |
          echo "::group::Install Proj (via apt-get)"
          sudo apt-get -y update && sudo apt-get install --no-install-recommends -y libproj-dev proj-bin
          echo "::endgroup::"
    - name: Install Proj (via brew)
      shell: bash
      if: runner.os == 'macOS'
      run: |
          echo "::group::Install Proj (via brew)"
          brew install proj
          echo "::endgroup::"
