name: Install HDF5
runs:
  using: "composite"
  steps:
    - name: Install HDF5 (via apt-get)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install HDF5 (via apt-get)"
            sudo apt-get -y update && sudo apt-get install libhdf5-dev
            echo "::endgroup::"
          fi
    - name: Install HDF5 (via brew)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'macOS' ) }}; then
            echo "::group::Install HDF5 (via brew)"
            brew install hdf5
            echo "::endgroup::"
          fi
