name: Install dependencies for PDL
runs:
  using: "composite"
  steps:
    - name: Install main PDL deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' ) }}; then
          echo "::group::Install main PDL deps (via apt-get)"
          sudo apt-get -y update && sudo apt-get install build-essential libgd-dev libhdf4-alt-dev libproj-dev proj-bin libcfitsio-dev libreadline-dev libvpx-dev libgsl0-dev libnetpbm10-dev
          echo "::endgroup::"
        elif ${{ toJSON( runner.os == 'macOS' ) }}; then
          echo "::group::Install main PDL deps (via brew)"
          brew install proj netpbm ffmpeg gsl gfortran
          echo "::endgroup::"
        fi
    - name: Install PGPLOT
      uses: PDLPorters/devops/github-actions/install-pgplot@master
    - name: Install extra optional main PDL deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' || runner.os == 'macOS' ) }}; then
          echo "::group::Install extra optional main PDL deps (via cpanm)"
          cpanm -n Term::ReadLine::Gnu PGPLOT Alien::HDF4 Alien::proj Inline::C || cat ~/.cpanm/build.log
          echo "::endgroup::"
        fi
    - name: Install OpenGL PDL deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' ) }}; then
          echo "::group::Install OpenGL PDL deps (via apt-get)"
          sudo apt-get install libx11-dev libxpm-dev libxi-dev libxmu-dev freeglut3-dev
          echo "::endgroup::"
        fi
    - name: Install extra optional OpenGL PDL deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' ) }}; then
          echo "::group::Install extra optional OpenGL PDL deps (via cpanm)"
          xvfb-run cpanm -n OpenGL || cat ~/.cpanm/build.log
          echo "::endgroup::"
        fi
