name: Install dependencies for PDL
runs:
  using: "composite"
  steps:
    - name: Install main PDL deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' ) }}; then
          echo "::group::Install main PDL deps (via apt-get)"
          sudo apt-get -y update && \
            sudo apt-get install --no-install-recommends -y build-essential libcfitsio-dev libreadline-dev libvpx-dev libgsl0-dev netpbm libnetpbm10-dev
          echo "::endgroup::"
        elif ${{ toJSON( runner.os == 'macOS' ) }}; then
          echo "::group::Install main PDL deps (via brew)"
          brew update
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install netpbm gsl
          echo "::endgroup::"
        fi
    - name: Install extra optional main PDL deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' || runner.os == 'macOS' ) }}; then
          echo "::group::Install extra optional main PDL deps (via cpanm)"
          cpanm -n Term::ReadLine::Gnu Inline::C || cat ~/.cpanm/build.log
          cpanm -n --reinstall Alien::proj || cat ~/.cpanm/build.log # in case has old path
          echo "::endgroup::"
        fi
    - name: Install OpenGL PDL deps
      uses: Perl-GPU/devops/github-actions/install-dep-pogl-dep@main
      if: runner.os == 'Linux'
    - name: Install extra optional OpenGL PDL deps
      shell: bash
      run: |
        if ${{ toJSON( runner.os == 'Linux' ) }}; then
          echo "::group::Install extra optional OpenGL PDL deps (via cpanm)"
          xvfb-run cpanm -n OpenGL OpenGL::GLUT || cat ~/.cpanm/build.log
          echo "::endgroup::"
        fi
