name: Install FFTW3
runs:
  using: "composite"
  steps:
    - name: Install FFTW3 (via apt-get)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install FFTW3 (via apt-get)"
            sudo apt-get install libfftw3-dev
            echo "::endgroup::"
          fi
    - name: Install FFTW3 (via brew)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'macOS' ) }}; then
            echo "::group::Install FFTW3 (via brew)"
            brew install fftw
            echo "::endgroup::"
          fi
    - name: Install FFTW3 (via Alien::FFTW3)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Windows' ) }}; then
            echo "::group::Install FFTW3 (via Alien::FFTW3 TODO)"
            # TODO Alien::FFTW3 does not have build support for MSWin32 yet
            #$MYPERL -S cpanm -n Module::Build
            #$MYPERL -S cpanm -n Alien::FFTW3
            echo "::endgroup::"
          fi
