name: Install LAPACK
runs:
  using: "composite"
  steps:
    - uses: PDLPorters/devops/github-actions/install-dep-gfortran@master
    - name: Install LAPACK (via apt-get)
      shell: bash
      if: runner.os == 'Linux'
      run: |
            echo "::group::Install LAPACK (via apt-get)"
            sudo apt-get -y update && sudo apt-get install --no-install-recommends -y liblapack-dev
            echo "::endgroup::"
    - name: Install LAPACK (via brew)
      shell: bash
      if: runner.os == 'macOS'
      run: |
          echo "::group::Install LAPACK (via brew)"
          brew install lapack
          echo "::endgroup::"
