name: Install LAPACK
runs:
  using: "composite"
  steps:
    - uses: PDLPorters/devops/github-actions/install-dep-gfortran@master
    - name: Install LAPACK (via apt-get)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install LAPACK (via apt-get)"
            sudo apt-get -y update && sudo apt-get install liblapack-dev
            echo "::endgroup::"
          fi
    - name: Install LAPACK (via brew)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'macOS' ) }}; then
            echo "::group::Install LAPACK (via brew)"
            brew install lapack
            echo "::endgroup::"
          fi
