name: IRC notifications
inputs:
  repository:
    description: Repository that notifications are triggered for.
    required: true
  irc_channel:
    required: true
    default: '#pdl-irc-test'
  irc_server:
    required: true
    default: 'irc.perl.org'
  irc_port:
    required: true
    default: '6667'
  irc_nickname:
    required: true
    default: 'pdl-commits-irc-test'
  irc_tls:
    required: true
    default: false
  irc_notice:
    required: true
    default: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: Gottox/irc-message-action
        ref: v1.3
        path: .github/actions/irc-message-action
    - name: irc push (build messages)
      shell: bash
      run: |
          if ${{ toJSON( github.event_name == 'push' && github.repository == inputs.repository ) }}; then
            echo "commitmsg="$( git show -s --oneline ${{ join(github.event.commits.*.id, ' ') }} ) >> $GITHUB_ENV
          fi
    - name: irc push
      shell: bash
      run: |
          if ${{ toJSON( github.event_name == 'push' && github.repository == inputs.repository ) }}; then
            node .github/actions/irc-message-action/app.js
          fi
      env:
        INPUT_MESSAGE: |
          ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
          ${{ env.commitmsg }}
        # Common inputs for Gottox/irc-message-action@v1.3
        INPUT_CHANNEL: ${{ inputs.irc_channel }}
        INPUT_SERVER: ${{ inputs.irc_server }}
        INPUT_PORT: ${{ inputs.irc_port }}
        INPUT_NICKNAME: ${{ inputs.irc_nickname }}
        INPUT_TLS: ${{ inputs.irc_tls }}
        INPUT_NOTICE: ${{ inputs.irc_notice }}
    - name: irc pull request
      shell: bash
      run: |
          if ${{ toJSON( github.event_name == 'pull_request' && github.repository == inputs.repository ) }}; then
            node .github/actions/irc-message-action/app.js
          fi
      env:
        INPUT_MESSAGE: |
          ${{ github.actor }} ${{ github.event.action }} PR «${{ github.event.pull_request.title }}» ${{ github.event.pull_request.html_url }}
        # Common inputs for Gottox/irc-message-action@v1.3
        INPUT_CHANNEL: ${{ inputs.irc_channel }}
        INPUT_SERVER: ${{ inputs.irc_server }}
        INPUT_PORT: ${{ inputs.irc_port }}
        INPUT_NICKNAME: ${{ inputs.irc_nickname }}
        INPUT_TLS: ${{ inputs.irc_tls }}
        INPUT_NOTICE: ${{ inputs.irc_notice }}
    - name: irc tag created
      shell: bash
      run: |
          if ${{ toJSON( github.event_name == 'create' && github.event.ref_type == 'tag' && github.repository == inputs.repository   ) }}; then
            node .github/actions/irc-message-action/app.js
          fi
      env:
        INPUT_MESSAGE: |
          ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}
        # Common inputs for Gottox/irc-message-action@v1.3
        INPUT_CHANNEL: ${{ inputs.irc_channel }}
        INPUT_SERVER: ${{ inputs.irc_server }}
        INPUT_PORT: ${{ inputs.irc_port }}
        INPUT_NICKNAME: ${{ inputs.irc_nickname }}
        INPUT_TLS: ${{ inputs.irc_tls }}
        INPUT_NOTICE: ${{ inputs.irc_notice }}
    - name: irc issue
      shell: bash
      run: |
          if ${{ toJSON( github.event_name == 'issues' && github.repository == inputs.repository ) }}; then
            node .github/actions/irc-message-action/app.js
          fi
      env:
        INPUT_MESSAGE: |
          ${{ github.actor }} ${{ github.event.action }} issue #${{ github.event.issue.number }} ${{ github.event.issue.html_url }}
        # Common inputs for Gottox/irc-message-action@v1.3
        INPUT_CHANNEL: ${{ inputs.irc_channel }}
        INPUT_SERVER: ${{ inputs.irc_server }}
        INPUT_PORT: ${{ inputs.irc_port }}
        INPUT_NICKNAME: ${{ inputs.irc_nickname }}
        INPUT_TLS: ${{ inputs.irc_tls }}
        INPUT_NOTICE: ${{ inputs.irc_notice }}
    - name: irc comment
      shell: bash
      run: |
          if ${{ toJSON( github.event_name == 'issue_comment' && github.repository == inputs.repository ) }}; then
            node .github/actions/irc-message-action/app.js
          fi
      env:
        INPUT_MESSAGE: |
          ${{ github.actor }} ${{ github.event.review.state || 'commented' }} on #${{ github.event.issue.number }} ${{ github.event.comment.html_url || github.event.review.html_url }}
        # Common inputs for Gottox/irc-message-action@v1.3
        INPUT_CHANNEL: ${{ inputs.irc_channel }}
        INPUT_SERVER: ${{ inputs.irc_server }}
        INPUT_PORT: ${{ inputs.irc_port }}
        INPUT_NICKNAME: ${{ inputs.irc_nickname }}
        INPUT_TLS: ${{ inputs.irc_tls }}
        INPUT_NOTICE: ${{ inputs.irc_notice }}
