name: Install gfortran
runs:
  using: "composite"
  steps:
    - name: Install gfortran
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install gfortran (via apt-get)"
            sudo apt-get -y update && sudo apt-get install --no-install-recommends -y gfortran
            echo "::endgroup::"
          elif ${{ toJSON( runner.os == 'macOS' ) }}; then
            echo "::group::Install gfortran (via brew)"
            HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew reinstall gfortran # python@3.12 link problem
            echo "::endgroup::"
          fi
