name: Install NetCDF
runs:
  using: "composite"
  steps:
    - name: Install NetCDF (via apt-get)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install NetCDF (via apt-get)"
            sudo apt-get -y update && sudo apt-get install libnetcdf-dev
            echo "::endgroup::"
          fi
    - name: Install NetCDF (via brew)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'macOS' ) }}; then
            echo "::group::Install NetCDF (via brew)"
            brew install netcdf
            echo "::endgroup::"
          fi
