name: Install NetCDF
runs:
  using: "composite"
  steps:
    - name: Install NetCDF (via apt-get)
      shell: bash
      if: runner.os == 'Linux'
      run: |
          echo "::group::Install NetCDF (via apt-get)"
          sudo apt-get -y update && sudo apt-get install --no-install-recommends -y libnetcdf-dev
          echo "::endgroup::"
    - name: Install NetCDF (via brew)
      shell: bash
      if: runner.os == 'macOS'
          echo "::group::Install NetCDF (via brew)"
          brew install netcdf
          echo "::endgroup::"
