name: Install dependencies for Prima
runs:
  using: "composite"
  steps:
    - name: Install Prima deps (via apt-get)
      shell: bash
      if: runner.os == 'Linux'
      run: |
        echo "::group::Install Prima deps (via apt-get)"
        sudo apt-get -y update && \
          sudo apt-get install --no-install-recommends -y \
            libx11-dev \
            libgif-dev libjpeg-dev libtiff-dev libxpm-dev libwebp-dev \
            libfribidi-dev libharfbuzz-dev libthai-dev
        echo "::endgroup::"
    - name: Install Prima deps (MacOS)
      shell: bash
      if: runner.os == 'macOS'
      run: echo None
