name: Install OpenCV
runs:
  using: "composite"
  steps:
    - name: Install OpenCV (via apt-get)
      shell: bash
      if: runner.os == 'Linux'
      run: |
          echo "::group::Install OpenCV (via apt-get)"
          sudo apt-get -y update && sudo apt-get install --no-install-recommends -y libopencv-dev
          echo "::endgroup::"
    - name: Install OpenCV (via brew)
      shell: bash
      if: runner.os == 'macOS'
      run: brew install opencv
    - name: Install OpenCV (via Alien::OpenCV)
      shell: bash
      if: runner.os == 'Windows'
      run: |
          echo "::group::Install OpenCV (via Alien::OpenCV TODO)"
          # TODO Alien::OpenCV does not have build support for MSWin32 yet
          #$MYPERL -S cpanm -n Alien::OpenCV || ( cat ~/.cpanm/build.log && false )
          echo "::endgroup::"
