name: Make distribution using ExtUtils::MakeMaker
inputs:
  dist-perl-deps-configure:
    description: |
      List of Perl configure-time dependencies to install.
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Cache ~/perl5
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dist-locallib
        path: ~/perl5
    - name: Check for Makefile.PL
      shell: bash
      run: |
          echo "::group::Check for Makefile.PL"
          [ -f "Makefile.PL" ]
          echo "::endgroup::"
    - name: Perl version
      shell: bash
      run: |
          echo "::group::Perl version"
          perl -v
          echo "::endgroup::"
    - name: Install cpanm
      shell: bash
      run: |
          echo "::group::Install cpanm"
          curl -L https://cpanmin.us | perl - --sudo App::cpanminus
          echo "::endgroup::"
    - name: Install local::lib
      shell: bash
      run: |
          echo "::group::Install local::lib"
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          echo "::endgroup::"
    - name: Install ExtUtils::MakeMaker and configure deps
      shell: bash
      run: |
          echo "::group::Install ExtUtils::MakeMaker"
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm -n ExtUtils::MakeMaker
          if [ -n "${{ inputs.dist-perl-deps-configure }}" ]; then
            cpanm --dev -n ${{ inputs.dist-perl-deps-configure }} || ( cat ~/.cpanm/build.log && false )
          fi
          echo "::endgroup::"
    - name: Make distribution
      shell: bash
      run: |
          echo "::group::Make distribution"
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          perl Makefile.PL && make distdir DISTVNAME=build-dir
          echo "::endgroup::"
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./build-dir
