name: Install gfortran dependencies
runs:
  using: "composite"
  steps:
    - uses: PDLPorters/devops/github-actions/install-gfortran@master
    - name: Install ExtUtils::F77
      shell: bash
      run: |
          echo "::group::Install ExtUtils::F77 (via cpanm)"
          $MYPERL -S cpanm -n ExtUtils::F77 || cat ~/.cpanm/build.log
          echo "::endgroup::"
