name: Install gfortran dependencies
runs:
  using: "composite"
  steps:
    - name: Install gfortran
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install gfortran (via apt-get)"
            sudo apt-get -y update && sudo apt-get install gfortran
            echo "::endgroup::"
          fi
    - name: Install ExtUtils::F77
      shell: bash
      run: |
          echo "::group::Install ExtUtils::F77 (via cpanm)"
          $MYPERL -S cpanm -n ExtUtils::F77 || cat ~/.cpanm/build.log
          echo "::endgroup::"
