name: Install PLplot
runs:
  using: "composite"
  steps:
    - name: Install plplot (via apt-get)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install plplot (via apt-get)"
            sudo apt-get -y update && sudo apt-get install --no-install-recommends -y libplplot-dev plplot-driver-qt
            echo "::endgroup::"
          fi
    - name: Install plplot (via brew)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'macOS' ) }}; then
            echo "::group::Install plplot (via brew)"
            brew update
            brew upgrade python || true # currently (2024-03-30) 3.12 link fails
            HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install plplot
            echo "::endgroup::"
          fi
    - name: Install plplot (via Alien::PLplot)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Windows' ) }}; then
            echo "::group::Install plplot (via Alien::PLplot)"
            $MYPERL -S cpanm -n Alien::PLplot || ( cat ~/.cpanm/build.log && false )
            echo "::endgroup::"
          fi
