name: Install PLplot
runs:
  using: "composite"
  steps:
    - name: Install plplot (via apt-get)
      shell: bash
      if: runner.os == 'Linux'
      run: |
          echo "::group::Install plplot (via apt-get)"
          sudo apt-get -y update && sudo apt-get install --no-install-recommends -y libplplot-dev plplot-driver-qt
          echo "::endgroup::"
    - name: Install plplot (via brew)
      shell: bash
      if: runner.os == 'macOS'
      run: |
          echo "::group::Install plplot (via brew)"
          brew update
          brew upgrade python || true # currently (2024-03-30) 3.12 link fails
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 brew install plplot
          echo "::endgroup::"
    - name: Install plplot (via Alien::PLplot)
      shell: bash
      if: runner.os == 'Windows'
      run: |
          echo "::group::Install plplot (via Alien::PLplot)"
          $MYPERL -S cpanm -n Alien::PLplot || ( cat ~/.cpanm/build.log && false )
          echo "::endgroup::"
