name: issue-notify

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./github-actions/irc-notifications
