name: issue-notify

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }} && github.repository == 'PDLPorters/pdl'
    steps:
      - uses: PDLPorters/devops/github-actions/irc-notifications@master
        with:
          repository: PDLPorters/devops
