name: Install Gnuplot
runs:
  using: "composite"
  steps:
    - name: Install gnuplot (via apt-get)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Linux' ) }}; then
            echo "::group::Install gnuplot (via apt-get)"
            sudo apt-get -y update && sudo apt-get install --no-install-recommends -y gnuplot gnuplot-qt
            echo "::endgroup::"
          fi
    - name: Install gnuplot (via brew)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'macOS' ) }}; then
            echo "::group::Install gnuplot (via brew)"
            brew install gnuplot
            echo "::endgroup::"
          fi
    - name: Install gnuplot (extract from archive)
      shell: bash
      run: |
          if ${{ toJSON( runner.os == 'Windows' ) }}; then
            echo "::group::Install gnuplot (extract from archive)"
            pwsh -c ' [Net.ServicePointManager]::SecurityProtocol = "tls12, tls11, tls"; $request = Invoke-WebRequest -MaximumRetryCount 3 -UserAgent Curl -Uri  "https://sourceforge.net/projects/gnuplot/files/gnuplot/5.4.6/gp546-win64-mingw.7z/download" -OutFile "gp546-win64-mingw.7z"'
            7z x gp546-win64-mingw.7z -o..
            pwsh -c 'echo "'$( cygpath -w $( realpath ../gnuplot/bin ) )'" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append'
            echo "::endgroup::"
          fi
